name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths:
      - firebase/**

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g firebase-tools
      - run: firebase deploy